# Generated by Django 4.0.3 on 2022-03-14 11:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('slug', models.SlugField(max_length=250)),
                ('published', models.DateTimeField(verbose_name=datetime.datetime(2022, 3, 14, 11, 8, 14, 536627, tzinfo=utc))),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('link', models.URLField()),
                ('Category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='projecta.category')),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
    ]
