# Generated by Django 4.0.3 on 2022-03-14 12:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='some product', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 3, 14, 12, 4, 1, 365214, tzinfo=utc)),
        ),
    ]
