# Generated by Django 4.0.3 on 2022-03-14 12:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0002_product_description_alter_product_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 3, 14, 12, 6, 42, 212711, tzinfo=utc)),
        ),
    ]
