# Generated by Django 4.0.3 on 2022-03-15 08:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0003_alter_product_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='dropdown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='rows',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 3, 15, 8, 21, 21, 645010, tzinfo=utc)),
        ),
    ]
