# Generated by Django 4.0.3 on 2022-03-23 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0006_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.BooleanField(default=False)),
                ('dropdown', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Type',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projecta.type'),
        ),
    ]
